package filetypes

// Code generated from weavatrix-scan default_file_types.rs at 29c003a6.
// Do not edit by hand.

type typeDef struct {
	names    []string
	patterns []string
}

var catalog = []typeDef{
	{[]string{}, []string{}},
	{[]string{"ada"}, []string{"*.adb", "*.ads"}},
	{[]string{"agda"}, []string{"*.agda", "*.lagda"}},
	{[]string{"aidl"}, []string{"*.aidl"}},
	{[]string{"alire"}, []string{"alire.toml"}},
	{[]string{"alloy"}, []string{"*.als"}},
	{[]string{"amake"}, []string{"*.mk", "*.bp"}},
	{[]string{"angular"}, []string{"*.component.html", "*.component.scss", "*.component.ts"}},
	{[]string{"ansible"}, []string{"playbook*.yml", "playbook*.yaml", "roles/*/tasks/*.yml", "roles/*/tasks/*.yaml"}},
	{[]string{"asciidoc"}, []string{"*.adoc", "*.asc", "*.asciidoc"}},
	{[]string{"asm"}, []string{"*.asm", "*.s", "*.S"}},
	{[]string{"asp"}, []string{"*.aspx", "*.aspx.cs", "*.aspx.vb", "*.ascx", "*.ascx.cs", "*.ascx.vb", "*.asp"}},
	{[]string{"ats"}, []string{"*.ats", "*.dats", "*.sats", "*.hats"}},
	{[]string{"avro"}, []string{"*.avdl", "*.avpr", "*.avsc"}},
	{[]string{"awk"}, []string{"*.awk"}},
	{[]string{"bat", "batch"}, []string{"*.bat"}},
	{[]string{"bazel", "starlark"}, []string{"*.bazel", "*.bzl", "*.BUILD", "*.bazelrc", "*.star", "BUILD", "MODULE.bazel", "WORKSPACE", "WORKSPACE.bazel", "WORKSPACE.bzlmod"}},
	{[]string{"bicep"}, []string{"*.bicep", "*.bicepparam"}},
	{[]string{"bitbake"}, []string{"*.bb", "*.bbappend", "*.bbclass", "*.conf", "*.inc"}},
	{[]string{"biome"}, []string{"biome.json", "biome.jsonc"}},
	{[]string{"boxlang"}, []string{"*.bx", "*.bxm", "*.bxs"}},
	{[]string{"brotli"}, []string{"*.br"}},
	{[]string{"buck"}, []string{"BUCK", "BUCK.*", "*.buckconfig"}},
	{[]string{"buildstream"}, []string{"*.bst"}},
	{[]string{"bzip2"}, []string{"*.bz2", "*.tbz2"}},
	{[]string{"c"}, []string{"*.[chH]", "*.[chH].in", "*.cats"}},
	{[]string{"cabal"}, []string{"*.cabal"}},
	{[]string{"candid"}, []string{"*.did"}},
	{[]string{"carp"}, []string{"*.carp"}},
	{[]string{"cbor"}, []string{"*.cbor"}},
	{[]string{"ceylon"}, []string{"*.ceylon"}},
	{[]string{"cfml"}, []string{"*.cfc", "*.cfm"}},
	{[]string{"clojure"}, []string{"*.clj", "*.cljc", "*.cljs", "*.cljx"}},
	{[]string{"cmake"}, []string{"*.cmake", "CMakeLists.txt"}},
	{[]string{"cmd"}, []string{"*.bat", "*.cmd"}},
	{[]string{"cml"}, []string{"*.cml"}},
	{[]string{"coffeescript"}, []string{"*.coffee"}},
	{[]string{"config"}, []string{"*.cfg", "*.conf", "*.config", "*.ini"}},
	{[]string{"container"}, []string{"*Containerfile*", "*Dockerfile*"}},
	{[]string{"coq"}, []string{"*.v"}},
	{[]string{"cpp", "cxx"}, []string{"*.[ChH]", "*.cc", "*.[ch]pp", "*.[ch]xx", "*.hh", "*.inl", "*.[ChH].in", "*.cc.in", "*.[ch]pp.in", "*.[ch]xx.in", "*.hh.in"}},
	{[]string{"creole"}, []string{"*.creole"}},
	{[]string{"crystal"}, []string{"Projectfile", "*.cr", "*.ecr", "shard.yml"}},
	{[]string{"cs"}, []string{"*.cs"}},
	{[]string{"csharp"}, []string{"*.cs"}},
	{[]string{"cshtml"}, []string{"*.cshtml"}},
	{[]string{"csproj"}, []string{"*.csproj"}},
	{[]string{"css"}, []string{"*.css", "*.scss"}},
	{[]string{"csv"}, []string{"*.csv"}},
	{[]string{"cue"}, []string{"*.cue"}},
	{[]string{"cuda"}, []string{"*.cu", "*.cuh"}},
	{[]string{"cython"}, []string{"*.pyx", "*.pxi", "*.pxd"}},
	{[]string{"d"}, []string{"*.d"}},
	{[]string{"dart"}, []string{"*.dart"}},
	{[]string{"deno"}, []string{"deno.json", "deno.jsonc", "deno.lock"}},
	{[]string{"devicetree"}, []string{"*.dts", "*.dtsi", "*.dtso"}},
	{[]string{"dhall"}, []string{"*.dhall"}},
	{[]string{"diff"}, []string{"*.patch", "*.diff"}},
	{[]string{"dita"}, []string{"*.dita", "*.ditamap", "*.ditaval"}},
	{[]string{"docker"}, []string{"*Dockerfile*"}},
	{[]string{"dockercompose"}, []string{"docker-compose.yml", "docker-compose.*.yml", "compose.yml", "compose.yaml", "compose.*.yml", "compose.*.yaml"}},
	{[]string{"dotenv"}, []string{".env", ".env.*", "*.env"}},
	{[]string{"dts"}, []string{"*.dts", "*.dtsi"}},
	{[]string{"dvc"}, []string{"Dvcfile", "*.dvc"}},
	{[]string{"earthfile"}, []string{"Earthfile"}},
	{[]string{"ebuild"}, []string{"*.ebuild", "*.eclass"}},
	{[]string{"edn"}, []string{"*.edn"}},
	{[]string{"elisp"}, []string{"*.el"}},
	{[]string{"elixir"}, []string{"*.ex", "*.eex", "*.exs", "*.heex", "*.leex", "*.livemd"}},
	{[]string{"elm"}, []string{"*.elm"}},
	{[]string{"erb"}, []string{"*.erb"}},
	{[]string{"erlang"}, []string{"*.erl", "*.hrl"}},
	{[]string{"fennel"}, []string{"*.fnl"}},
	{[]string{"fidl"}, []string{"*.fidl"}},
	{[]string{"fish"}, []string{"*.fish"}},
	{[]string{"flatbuffers"}, []string{"*.fbs"}},
	{[]string{"fortran"}, []string{"*.f", "*.F", "*.f77", "*.F77", "*.pfo", "*.f90", "*.F90", "*.f95", "*.F95"}},
	{[]string{"fsharp"}, []string{"*.fs", "*.fsx", "*.fsi"}},
	{[]string{"fut"}, []string{"*.fut"}},
	{[]string{"gap"}, []string{"*.g", "*.gap", "*.gi", "*.gd", "*.tst"}},
	{[]string{"gdscript"}, []string{"*.gd"}},
	{[]string{"github-actions"}, []string{".github/actions/*.yml", ".github/actions/*.yaml", ".github/workflows/*.yml", ".github/workflows/*.yaml"}},
	{[]string{"gitlab-ci"}, []string{".gitlab-ci.yml", ".gitlab-ci.yaml"}},
	{[]string{"gleam"}, []string{"*.gleam"}},
	{[]string{"gn"}, []string{"*.gn", "*.gni"}},
	{[]string{"go"}, []string{"*.go"}},
	{[]string{"gprbuild"}, []string{"*.gpr"}},
	{[]string{"gradle"}, []string{"*.gradle", "*.gradle.kts", "gradle.properties", "gradle-wrapper.*", "gradlew", "gradlew.bat"}},
	{[]string{"graphql"}, []string{"*.graphql", "*.graphqls"}},
	{[]string{"groovy"}, []string{"*.groovy", "*.gradle"}},
	{[]string{"gzip"}, []string{"*.gz", "*.tgz"}},
	{[]string{"h"}, []string{"*.h", "*.hh", "*.hpp"}},
	{[]string{"haml"}, []string{"*.haml"}},
	{[]string{"hare"}, []string{"*.ha"}},
	{[]string{"haskell"}, []string{"*.hs", "*.lhs", "*.cpphs", "*.c2hs", "*.hsc"}},
	{[]string{"hbs"}, []string{"*.hbs"}},
	{[]string{"helm"}, []string{"Chart.yaml", "Chart.yml", "values.yaml", "values.yml", "values.*.yaml", "values.*.yml"}},
	{[]string{"hjson"}, []string{"*.hjson"}},
	{[]string{"hs"}, []string{"*.hs", "*.lhs"}},
	{[]string{"html"}, []string{"*.htm", "*.html", "*.ejs"}},
	{[]string{"hurl"}, []string{"*.hurl"}},
	{[]string{"hy"}, []string{"*.hy"}},
	{[]string{"idris"}, []string{"*.idr", "*.lidr"}},
	{[]string{"janet"}, []string{"*.janet"}},
	{[]string{"java"}, []string{"*.java", "*.jsp", "*.jspx", "*.properties"}},
	{[]string{"javascript", "js"}, []string{"*.js", "*.jsx", "*.vue", "*.cjs", "*.mjs"}},
	{[]string{"jinja"}, []string{"*.j2", "*.jinja", "*.jinja2"}},
	{[]string{"jl"}, []string{"*.jl"}},
	{[]string{"json"}, []string{"*.json", "composer.lock", "*.sarif"}},
	{[]string{"json5"}, []string{"*.json5"}},
	{[]string{"jsonc"}, []string{"*.jsonc"}},
	{[]string{"jsonl"}, []string{"*.jsonl", "*.ndjson"}},
	{[]string{"julia"}, []string{"*.jl"}},
	{[]string{"jupyter"}, []string{"*.ipynb", "*.jpynb"}},
	{[]string{"just"}, []string{"Justfile", "justfile", "*.just"}},
	{[]string{"k"}, []string{"*.k"}},
	{[]string{"kconfig"}, []string{"Kconfig", "Kconfig.*"}},
	{[]string{"kdl"}, []string{"*.kdl"}},
	{[]string{"kotlin"}, []string{"*.kt", "*.kts"}},
	{[]string{"kustomize"}, []string{"kustomization.yaml", "kustomization.yml", "Kustomization"}},
	{[]string{"lean"}, []string{"*.lean"}},
	{[]string{"less"}, []string{"*.less"}},
	{[]string{"license"}, []string{"COPYING", "COPYING[.-]*", "COPYRIGHT", "COPYRIGHT[.-]*", "EULA", "EULA[.-]*", "licen[cs]e", "licen[cs]e.*", "LICEN[CS]E", "LICEN[CS]E[.-]*", "*[.-]LICEN[CS]E*", "NOTICE", "NOTICE[.-]*", "PATENTS", "PATENTS[.-]*", "UNLICEN[CS]E", "UNLICEN[CS]E[.-]*", "agpl[.-]*", "gpl[.-]*", "lgpl[.-]*", "AGPL-*[0-9]*", "APACHE-*[0-9]*", "BSD-*[0-9]*", "CC-BY-*", "GFDL-*[0-9]*", "GNU-*[0-9]*", "GPL-*[0-9]*", "LGPL-*[0-9]*", "MIT-*[0-9]*", "MPL-*[0-9]*", "OFL-*[0-9]*"}},
	{[]string{"lilypond"}, []string{"*.ly", "*.ily"}},
	{[]string{"lisp"}, []string{"*.el", "*.jl", "*.lisp", "*.lsp", "*.sc", "*.scm"}},
	{[]string{"llvm"}, []string{"*.ll"}},
	{[]string{"lock"}, []string{"*.lock", "package-lock.json", "bun.lock", "bun.lockb", "pnpm-lock.yaml", "yarn.lock", "uv.lock", "Pipfile.lock", "poetry.lock"}},
	{[]string{"log"}, []string{"*.log"}},
	{[]string{"lua"}, []string{"*.lua"}},
	{[]string{"lz4"}, []string{"*.lz4"}},
	{[]string{"lzma"}, []string{"*.lzma"}},
	{[]string{"m4"}, []string{"*.ac", "*.m4"}},
	{[]string{"make"}, []string{"[Gg][Nn][Uu]makefile", "[Mm]akefile", "[Gg][Nn][Uu]makefile.am", "[Mm]akefile.am", "[Gg][Nn][Uu]makefile.in", "[Mm]akefile.in", "Makefile.*", "*.mk", "*.mak"}},
	{[]string{"mako"}, []string{"*.mako", "*.mao"}},
	{[]string{"man"}, []string{"*.[0-9lnpx]", "*.[0-9][cEFMmpSx]"}},
	{[]string{"markdown", "md"}, []string{"*.markdown", "*.md", "*.mdown", "*.mdwn", "*.mkd", "*.mkdn", "*.mdx"}},
	{[]string{"matlab"}, []string{"*.m"}},
	{[]string{"meson"}, []string{"meson.build", "meson_options.txt", "meson.options"}},
	{[]string{"minified"}, []string{"*.min.html", "*.min.css", "*.min.js"}},
	{[]string{"mint"}, []string{"*.mint"}},
	{[]string{"mk"}, []string{"mkfile"}},
	{[]string{"ml"}, []string{"*.ml"}},
	{[]string{"mojo"}, []string{"*.mojo", "*.🔥"}},
	{[]string{"motoko"}, []string{"*.mo"}},
	{[]string{"msbuild"}, []string{"*.csproj", "*.fsproj", "*.vcxproj", "*.proj", "*.props", "*.targets", "*.sln", "*.slnf", "*.slnx"}},
	{[]string{"nickel"}, []string{"*.ncl"}},
	{[]string{"nim"}, []string{"*.nim", "*.nimf", "*.nimble", "*.nims"}},
	{[]string{"nix"}, []string{"*.nix"}},
	{[]string{"nushell"}, []string{"*.nu"}},
	{[]string{"objc"}, []string{"*.h", "*.m"}},
	{[]string{"objcpp"}, []string{"*.h", "*.mm"}},
	{[]string{"ocaml"}, []string{"*.ml", "*.mli", "*.mll", "*.mly"}},
	{[]string{"openapi"}, []string{"openapi*.json", "openapi*.yaml", "openapi*.yml", "swagger*.json", "swagger*.yaml", "swagger*.yml"}},
	{[]string{"org"}, []string{"*.org", "*.org_archive"}},
	{[]string{"pants"}, []string{"BUILD"}},
	{[]string{"pascal"}, []string{"*.pas", "*.dpr", "*.lpr", "*.pp", "*.inc"}},
	{[]string{"pdf"}, []string{"*.pdf"}},
	{[]string{"perl"}, []string{"*.perl", "*.pl", "*.PL", "*.plh", "*.plx", "*.pm", "*.t"}},
	{[]string{"php"}, []string{"*.php", "*.php3", "*.php4", "*.php5", "*.php7", "*.php8", "*.pht", "*.phtml"}},
	{[]string{"pkgbuild"}, []string{"PKGBUILD"}},
	{[]string{"pkl"}, []string{"*.pkl"}},
	{[]string{"po"}, []string{"*.po"}},
	{[]string{"pod"}, []string{"*.pod"}},
	{[]string{"postscript"}, []string{"*.eps", "*.ps"}},
	{[]string{"powershell", "ps"}, []string{"*.cdxml", "*.ps1", "*.ps1xml", "*.psd1", "*.psm1"}},
	{[]string{"prisma"}, []string{"*.prisma"}},
	{[]string{"prolog"}, []string{"*.pl", "*.pro", "*.prolog", "*.P"}},
	{[]string{"proto", "protobuf"}, []string{"*.proto"}},
	{[]string{"puppet"}, []string{"*.epp", "*.erb", "*.pp", "*.rb"}},
	{[]string{"purs"}, []string{"*.purs"}},
	{[]string{"py", "python"}, []string{"*.py", "*.pyi", "*.pyw"}},
	{[]string{"qmake"}, []string{"*.pro", "*.pri", "*.prf"}},
	{[]string{"qml"}, []string{"*.qml"}},
	{[]string{"qrc"}, []string{"*.qrc"}},
	{[]string{"qui"}, []string{"*.ui"}},
	{[]string{"r"}, []string{"*.R", "*.r", "*.Rmd", "*.rmd", "*.Rnw", "*.rnw"}},
	{[]string{"racket"}, []string{"*.rkt"}},
	{[]string{"raku"}, []string{"*.raku", "*.rakumod", "*.rakudoc", "*.rakutest", "*.p6", "*.pl6", "*.pm6"}},
	{[]string{"rdoc"}, []string{"*.rdoc"}},
	{[]string{"readme"}, []string{"README*", "*README"}},
	{[]string{"reasonml"}, []string{"*.re", "*.rei"}},
	{[]string{"red"}, []string{"*.r", "*.red", "*.reds"}},
	{[]string{"rego"}, []string{"*.rego"}},
	{[]string{"rescript"}, []string{"*.res", "*.resi"}},
	{[]string{"robot"}, []string{"*.robot"}},
	{[]string{"rocq"}, []string{"*.v"}},
	{[]string{"ron"}, []string{"*.ron"}},
	{[]string{"rst"}, []string{"*.rst"}},
	{[]string{"ruby"}, []string{"config.ru", "Gemfile", ".irbrc", "Rakefile", "*.gemspec", "*.rb", "*.rbw", "*.rake"}},
	{[]string{"rust", "rs"}, []string{"*.rs"}},
	{[]string{"sass"}, []string{"*.sass", "*.scss"}},
	{[]string{"scala"}, []string{"*.scala", "*.sbt"}},
	{[]string{"scdoc"}, []string{"*.scd", "*.scdoc"}},
	{[]string{"seed7"}, []string{"*.sd7", "*.s7i"}},
	{[]string{"sh", "shell"}, []string{".env", ".login", ".logout", ".profile", "profile", ".bash_login", "bash_login", ".bash_logout", "bash_logout", ".bash_profile", "bash_profile", ".bashrc", "bashrc", "*.bashrc", ".cshrc", "*.cshrc", ".kshrc", "*.kshrc", ".tcshrc", ".zshenv", "zshenv", ".zlogin", "zlogin", ".zlogout", "zlogout", ".zprofile", "zprofile", ".zshrc", "zshrc", "*.bash", "*.csh", "*.env", "*.ksh", "*.sh", "*.tcsh", "*.zsh"}},
	{[]string{"slim"}, []string{"*.skim", "*.slim", "*.slime"}},
	{[]string{"slint"}, []string{"*.slint"}},
	{[]string{"smarty"}, []string{"*.tpl"}},
	{[]string{"sml"}, []string{"*.sml", "*.sig"}},
	{[]string{"smithy"}, []string{"*.smithy"}},
	{[]string{"solidity"}, []string{"*.sol"}},
	{[]string{"soy"}, []string{"*.soy"}},
	{[]string{"spark"}, []string{"*.spark"}},
	{[]string{"spec"}, []string{"*.spec"}},
	{[]string{"sql"}, []string{"*.sql", "*.psql", "*.ddl", "*.dml"}},
	{[]string{"ssa"}, []string{"*.ssa"}},
	{[]string{"stylus"}, []string{"*.styl"}},
	{[]string{"sv"}, []string{"*.v", "*.vg", "*.sv", "*.svh", "*.h"}},
	{[]string{"svelte"}, []string{"*.svelte", "*.svelte.ts"}},
	{[]string{"svg"}, []string{"*.svg"}},
	{[]string{"swift"}, []string{"*.swift"}},
	{[]string{"swig"}, []string{"*.def", "*.i"}},
	{[]string{"systemd"}, []string{"*.automount", "*.conf", "*.device", "*.link", "*.mount", "*.path", "*.scope", "*.service", "*.slice", "*.socket", "*.swap", "*.target", "*.timer"}},
	{[]string{"taskpaper"}, []string{"*.taskpaper"}},
	{[]string{"tcl"}, []string{"*.tcl"}},
	{[]string{"templ"}, []string{"*.templ"}},
	{[]string{"terraform", "tf"}, []string{"*.tf", "*.tf.json", "*.tfvars", "*.tfvars.json", "*.terraformrc", "terraform.rc", "*.tfrc", "*.terraform.lock.hcl"}},
	{[]string{"tex"}, []string{"*.tex", "*.ltx", "*.cls", "*.sty", "*.bib", "*.dtx", "*.ins"}},
	{[]string{"texinfo"}, []string{"*.texi"}},
	{[]string{"textile"}, []string{"*.textile"}},
	{[]string{"thrift"}, []string{"*.thrift"}},
	{[]string{"tilt"}, []string{"Tiltfile"}},
	{[]string{"toml"}, []string{"*.toml", "Cargo.lock"}},
	{[]string{"ts", "typescript"}, []string{"*.ts", "*.tsx", "*.cts", "*.mts"}},
	{[]string{"twig"}, []string{"*.twig"}},
	{[]string{"txt"}, []string{"*.txt"}},
	{[]string{"typoscript"}, []string{"*.typoscript", "*.ts"}},
	{[]string{"typst"}, []string{"*.typ"}},
	{[]string{"usd"}, []string{"*.usd", "*.usda", "*.usdc"}},
	{[]string{"v"}, []string{"*.v", "*.vsh"}},
	{[]string{"vala"}, []string{"*.vala"}},
	{[]string{"vb"}, []string{"*.vb"}},
	{[]string{"vcl"}, []string{"*.vcl"}},
	{[]string{"verilog"}, []string{"*.v", "*.vh", "*.sv", "*.svh"}},
	{[]string{"vhdl"}, []string{"*.vhd", "*.vhdl"}},
	{[]string{"vim"}, []string{"*.vim", ".vimrc", ".gvimrc", "vimrc", "gvimrc", "_vimrc", "_gvimrc"}},
	{[]string{"vimscript"}, []string{"*.vim", ".vimrc", ".gvimrc", "vimrc", "gvimrc", "_vimrc", "_gvimrc"}},
	{[]string{"vue"}, []string{"*.vue"}},
	{[]string{"wasm-text"}, []string{"*.wat", "*.wast"}},
	{[]string{"webidl"}, []string{"*.idl", "*.webidl", "*.widl"}},
	{[]string{"wgsl"}, []string{"*.wgsl"}},
	{[]string{"wiki"}, []string{"*.mediawiki", "*.wiki"}},
	{[]string{"wit"}, []string{"*.wit"}},
	{[]string{"xml"}, []string{"*.xml", "*.xml.dist", "*.dtd", "*.xsl", "*.xslt", "*.xsd", "*.xjb", "*.rng", "*.sch", "*.xhtml"}},
	{[]string{"xonsh"}, []string{"*.xsh"}},
	{[]string{"xz"}, []string{"*.xz", "*.txz"}},
	{[]string{"yacc"}, []string{"*.y"}},
	{[]string{"yaml", "yml"}, []string{"*.yaml", "*.yml"}},
	{[]string{"yang"}, []string{"*.yang"}},
	{[]string{"z"}, []string{"*.Z"}},
	{[]string{"zig"}, []string{"*.zig", "*.zon"}},
	{[]string{"zsh"}, []string{".zshenv", "zshenv", ".zlogin", "zlogin", ".zlogout", "zlogout", ".zprofile", "zprofile", ".zshrc", "zshrc", "*.zsh"}},
	{[]string{"zstd"}, []string{"*.zst", "*.zstd"}},
}
